version: '3.9'
services:
  server:
    build: .
    ports:
      - '3000:3000'
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npx sequelize-cli db:migrate && npm start'
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - '5432:5432'    
    environment:
      POSTGRES_USER: 'ui_test'
      POSTGRES_PASSWORD: 'password'      
      POSTGRES_DATABASE: 'ui_test'

